### ISSUE TITLE
Некорректная обработка статуса заказа при проверке

### ISSUE THREAD

**Issue by PeterBeklemishev** [madprogrammer/django-sberbank#1]
https://github.com/madprogrammer/django-sberbank/blob/master/sberbank/service.py#L196
orderStatus = 5 не является ошибочным, см https://securepayments.sberbank.ru/wiki/doku.php/integration:api:rest:requests:getorderstatusextended

**Comment by madprogrammer** [comment]
Не могли бы вы пояснить более конкретно в чем заключается проблема? В документации код ответа 5 означает

    5 | Доступ запрещён.
    5 | Пользователь должен сменить свой пароль.
    5 | [orderId] не задан.

Во всех перечисленных случаях платеж банком не проводится, что обрабатывается как ошибочная ситуация.

**Comment by PeterBeklemishev** [comment]
@madprogrammer возможно, вы путаете с полем `errorCode`?
(с документацией про который совпадает ваша расшифровка)
![image](https://user-images.githubusercontent.com/6017925/50401681-18f16080-07c3-11e9-9643-b636df7f6bd1.png)

**Comment by madprogrammer** [comment]
Действительно. Поправлю, спасибо.

**Comment by shoytov** [comment]
Выскакивает ошибка - 'Merchant key  not found in MERCHANTS' при успешной оплате с редиректом на урл - ...sberbank/payment/success... как должен выглядеть этот MERCHANT_KEY? Токен не подходит...
